# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Nakayama Itsuki'
description: ''
permalink: pretty
logo: "https://ul.h3z.jp/mQa6r4dl.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
# - title: Blog
#   url: /blog/

# Footer nav
# navigation_footer:
# - title: Back to top
#   url: "#top"
navigation_footer:
- title: Back to top
  url: "javascript:window.scrollTo(0, 0);"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "メモや日記などを書きます．"
    feature_text: |

    # feature_image: "https://picsum.photos/2560/600?image=866"
    feature_image: "https://ul.h3z.jp/UttoptFW.jpg"


# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

fonts:
  - url: "https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
    name: "Roboto"

# Site favicon
favicon: /favicon.ico
apple_touch_icon: /apple-touch-icon.png